version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: struts_demo_pg
    environment:
      POSTGRES_DB: strutsdb
      POSTGRES_USER: struts
      POSTGRES_PASSWORD: struts
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
